name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: village_loans_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Install sqlx-cli
      run: cargo install sqlx-cli

    - name: Set up database
      run: |
        export DATABASE_URL=postgres://postgres:password@localhost:5432/village_loans_test
        sqlx database create
        sqlx migrate run

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
